version: '3.8'

services:
    app:
        image: node:12-alpine
        build:
            context: .
            dockerfile: Dockerfile
        volumes: 
            - '.:/app'
            - '/app/node_modules'
            - ./:/app:cached
        working_dir: /app
        ports:
            - 3000:3000
        command: npm start
        tty: true
